- name: Copy Nginx repository file
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: '0644'

- name: Install the latest version of Nginx
  yum:
    name: nginx
    state: latest
  notify:
     - nginx service

- name: Copy Nginx configuration template
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  notify:
     - nginx service

- name: Copy Nginx index file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
     - nginx service
